### ISSUE TITLE
EACCESS relations.json when non-root

### ISSUE THREAD

**Issue by aravindet** [timqian/jsCodeStructure#3]
Running jss as non-root user gives the following error

```
$ jss --ignore node_modules bower_components
[ 'node_modules' ]
[ 'node_modules', 'bower_components' ]
/usr/lib/node_modules/js-code-structure/bin/jss.js:26
  if (err) throw err;
                 ^
Error: EACCES, open '/usr/lib/node_modules/js-code-structure/bin/relations.json'
    at Error (native)
```

It does not show this error while running as root.

I am using Arch Linux and I installed jss using `npm install -g`

**Comment by timqian** [comment]
Maybe it's because the user have no access to the directory: `/usr/lib/node_modules/js-code-structure/bin/`. Because the output html file is made up of files in that dir.(Maybe I will change this later)
Hope it helps, I am not vary familiar with linux.(I made this software on mac)

**Comment by timqian** [comment]
This bug is fixed.... try the new version. Sorry for the really long delay
